# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
timesThree <- function(x) {
    .Call('_chinaTrading_timesThree', PACKAGE = 'chinaTrading', x)
}

#' @export
getMean <- function(x) {
    .Call('_chinaTrading_getMean', PACKAGE = 'chinaTrading', x)
}

#' @export
getSharpe <- function(x) {
    .Call('_chinaTrading_getSharpe', PACKAGE = 'chinaTrading', x)
}

#' @export
getSD <- function(x) {
    .Call('_chinaTrading_getSD', PACKAGE = 'chinaTrading', x)
}

