# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' testing function
#' @export
#' @param x vector
timesThree <- function(x) {
    .Call('_chinaTrading_timesThree', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getMean <- function(x) {
    .Call('_chinaTrading_getMean', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getSharpe <- function(x) {
    .Call('_chinaTrading_getSharpe', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getSD <- function(x) {
    .Call('_chinaTrading_getSD', PACKAGE = 'chinaTrading', x)
}

#' get ticker function
#' @export
#' @param s vector
getTicker <- function(s) {
    .Call('_chinaTrading_getTicker', PACKAGE = 'chinaTrading', s)
}

#' get one ticker(not vectorized)
#' @export
#' @param s one string
getOneTicker <- function(s) {
    .Call('_chinaTrading_getOneTicker', PACKAGE = 'chinaTrading', s)
}

#' identity function
#' @export
#' @param x vector
getSum <- function(x) {
    .Call('_chinaTrading_getSum', PACKAGE = 'chinaTrading', x)
}

#' get sumChg, sumChgSq, n, sr of a change series in list
#' @export
#' @param x numvec
getSumChgC <- function(x) {
    .Call('_chinaTrading_getSumChgC', PACKAGE = 'chinaTrading', x)
}

#' get cumu sharpe
#' @export
#' @param x numvec
getDayCumSharpeCpp <- function(x) {
    .Call('_chinaTrading_getDayCumSharpeCpp', PACKAGE = 'chinaTrading', x)
}

#' take a data frame and get percentile
#' @export
#' @param x dataframe
getPercentileCpp <- function(x) {
    .Call('_chinaTrading_getPercentileCpp', PACKAGE = 'chinaTrading', x)
}

#' calc sharpe
#' @export
#' @param x retList
calcSharpeCpp <- function(x) {
    .Call('_chinaTrading_calcSharpeCpp', PACKAGE = 'chinaTrading', x)
}

