# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' testing function
#' @export
#' @param x vector
timesThree <- function(x) {
    .Call('_chinaTrading_timesThree', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getMean <- function(x) {
    .Call('_chinaTrading_getMean', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getSharpe <- function(x) {
    .Call('_chinaTrading_getSharpe', PACKAGE = 'chinaTrading', x)
}

#' testing function
#' @export
#' @param x vector
getSD <- function(x) {
    .Call('_chinaTrading_getSD', PACKAGE = 'chinaTrading', x)
}

